### ISSUE TITLE
Parent of node in subgraph is order dependent

### ISSUE THREAD

**Issue by dstockwell** [cpettitt/graphlib-dot#21]
```
var dot = require('graphlib-dot');
var graph1 = dot.read('digraph g { a -> b; subgraph cluster0 { b -> c; } }');
console.log(graph1.parent('b'));
var graph2 = dot.read('digraph g { subgraph cluster0 { b -> c; } a -> b; }');
console.log(graph2.parent('b'));
```

outputs: 

```
undefined
cluster0
```

However graphviz renders `b` as being inside the subgraph in both cases.

**Comment by cpettitt** [comment]
Interesting.

The DOT language is order dependent. If you have this:

```dot
digraph g { subgraph cluster0 { b -> c; } subgraph cluster1 { b -> d; } }
```

Then you end up with cluster0 being the parent for b. Similarly for:

```dot
digraph g { a -> b; subgraph cluster0 { b -> c; } subgraph cluster1 { b -> d; } }
```

It seems that graphviz is treating root graphs and subgraphs differently. If a node in the root graph later appears in a subgraph it is moved to the first subgraph. If a node in a subgraph later appears in another subgraph it is left in the original subgraph.

This is a case where I prefer the consistency of the rules (first declaration wins) over the consistency with graphviz behavior.
