### ISSUE TITLE
Error parsing with HTML in document

### ISSUE THREAD

**Issue by cmdcolin** [cpettitt/graphlib-dot#27]
Works

```
digraph graphname {
    node [shape=plaintext];
    rankdir=LR;
    1 [shape=none,width=0,height=0,margin=0,rank=min,pos="-1500, -10"];
}
```

Doesn't work

```
digraph graphname {
    node [shape=plaintext];
    rankdir=LR;
    1 [shape=none,width=0,height=0,margin=0,rank=min,pos="-1500, -10",label=<<B>Hello world</B>>];
}
```

The comment about HTML IDs not being supported in the parser might already mention this limitation https://github.com/cpettitt/graphlib-dot/blob/master/src/dot-grammar.pegjs

**Comment by cpettitt** [comment]
Set labelType="html":

http://cpettitt.github.io/project/dagre-d3/latest/demo/interactive-demo.html?graph=digraph%20%7B%0A%20%20%20%20a%20%5BlabelType%3D%22html%22%20label%3D%22%3Cb%3Etest%3C%2Fb%3E%22%5D%3B%0A%7D
